services:

  server:
    image: wallet
    build: .
    env_file:
      - ./config.env
    ports:
      - 50051:50051
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: walletdb
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
